### ISSUE TITLE
synced deps not commited 

### ISSUE THREAD

**Issue by as3mbus** [reeseschultz/ubump#11]
```
? The 'A3 Utilities' dependencies are out of sync with the containing project. Sync them? Yes
? What is the type of change for the A3 Utilities package? Minor       1.1.0
? Are you sure you're happy with 1.1.0? Yes

? Want to commit your changes? Yes, commit with 'Bump project to v0.2.0; A3 Audio Control Unity to v0.0.4; A3 Audio Control to v0.0.4; A3 Code Pattern to v0.0.4; NSubstitute Wrapper to v0.0.4; A3 Quiz to v0.0.4; A3 Timer to v1.0.1; A3 UGUI Display to v0.0.2; A3 Uti
lities to v1.1.0' as the commit message.
? Push the changes? Yes
? Are you sure? Yes

Successfully pushed commit tagged with v0.2.0.

? Push a subtree branch for each package, tagging accordingly? Yes
? Are you sure? Yes
\ Splitting A3 Audio Control Unity with unity as the branch name.(node:17804) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: git checkout unity
error: Your local changes to the following files would be overwritten by checkout:
        Packages/com.a3.audio-control.unity/package.json
        Packages/com.a3.ugui-display/package.json
Please commit your changes or stash them before you switch branches.
Aborting
    at makeError (C:\Users\Crew\AppData\Roaming\npm\node_modules\ubump\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\Crew\AppData\Roaming\npm\node_modules\ubump\node_modules\execa\index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
- Splitting A3 Audio Control Unity with unity as the branch name.Terminate batch job (Y/N)? Y
```

i assume the ordering of ubump package bump seems to be the cause of this problem. 

since i have bumped previous package that depend on later bumped package e.g 

example :
com.a3.audio have dependencies with com.a3.utility
1. com.a3.audio got bumped (change staged)
2. com.a3.utility got bumped. (change staged)
3. com.a3.audio get synced with com.a3.utility bump (create change not staged) 
4. trying to split the package. 
5. local change prevent the split command

**Comment by reeseschultz** [comment]
Thanks for the log, and explanation of the problem. I think you're right about the order. I'll do some testing and get back to you on this.

**Comment by as3mbus** [comment]
i wonder why it require to check out when splitting the tree, when i could just split the branch without any checkout?

**Comment by reeseschultz** [comment]
I believe it has to do with getting tags right.

Since you're a programmer and you seem very interested in this issue, I'll remind you that you do have the ability to submit a PR and fix it. I wanted to get to this issue earlier, but I've had higher priorities. Would you be interested in tackling this issue?

**Comment by as3mbus** [comment]
i'd love to. but im not that experienced with npm. so i might take more time. but i'll try in my free time regardless
