### ISSUE TITLE
Subtree split ignores `--project-path` argument

### ISSUE THREAD

**Issue by robinnorth** [reeseschultz/ubump#17]
When running the CLI with a `--project-path` argument specified, ubump seemingly ignores this when attempting to split packages into git subtrees, resulting in an unhandled Promise rejection and the CLI hanging:

`$ ubump --project-path='src/Unity/unity-packages'`

```
\ Splitting Test Package with testpackage as the branch name.(node:51168) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: git subtree split -P Packages/com.example.testpackage -b testpackage 
You need to run this command from the toplevel of the working tree.
    at makeError (D:\Repos\unity-packages\node_modules\execa\lib\error.js:59:11)
    at handlePromise (D:\Repos\unity-packages\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async D:\Repos\unity-packages\node_modules\ubump\src\inquiry.js:473:9
    at async D:\Repos\unity-packages\node_modules\ubump\src\cli.js:372:7
(node:51168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:51168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

You can see that `git subtree split` is passed `Packages/com.example.testpackage` as the prefix argument, when in this example it should be `src/Unity/unity-packages/Packages/com.example.testpackage`

**Comment by robinnorth** [comment]
After a bit of hacking on ubump and experimentation on the command line, I've not been able to get `git --git-dir <path/to/.git> subtree split` to work as intended, at least with the version of Git I'm using (`git version 2.27.0.windows.1`). It fails to find any revisions to split at, despite passing in a correct tree prefix argument.

However, temporarily `chdir`-ing to the top level of the git repo (you can determine this with `git rev-parse --show-toplevel`), running the subtree split and then changing back to the original working directory ubump sets based on `--project-path` _does_ seem to work.

I can submit a PR for the changes when I've had a chance to test them more thoroughly. Currently I have still yet to successfully get ubump to work with my test monorepo, as although the change I've described above now allows me to split subtrees for packages, I have encountered a further issue to with tagging subtree branch commits, which I'll open a new issue for when I've done some more troubleshooting to determine the cause.

**Comment by reeseschultz** [comment]
Hi @robinnorth, I really appreciate that you're looking into this and the tagging problem. Thank you for submitting this issue, and I'll look forward to your PR. If you need help in the meantime, please let me know.
